webcamp-menber-donuts/NaganoCake

app/views/admin/customers/edit.html.erb, app/views/admin/customers/index.html.erb, app/views/admin/customers/show.html.erb, app/views/admin/homes/top.html.erb, app/views/layouts/application.html.erb, app/views/public/customers/withdrawal_check.html.erb
=> [add]ヘッダー、フッター

app/controllers/admin/product_genres_controller.rb, app/views/admin/product_genres/edit.html.erb, app/views/admin/product_genres/index.html.erb
商品ジャンル関係の下記、３ファイル変更しました。
①app/controllers/admin/product_genres_controller.rb
②app/views/admin/product_genres/edit.html.erb
③app/views/admin/product_genres/index.html.erb
=> [Finish]product_genre

app/controllers/admin/sessions_controller.rb, app/controllers/application_controller.rb, app/controllers/public/sessions_controller.rb, app/models/admin.rb, app/views/admin/customers/edit.html.erb, app/views/admin/homes/top.html.erb, app/views/admin/sessions/new.html.erb, app/views/admin/shared/_links.html.erb, db/seeds.rb
=> Feature admin

app/controllers/public/customers_controller.rb, app/models/customer.rb, app/views/layouts/application.html.erb, app/views/public/customers/edit.html.erb, app/views/public/customers/show.html.erb, app/views/public/homes/top.html.erb
ヘッダーにログアウトリンク追加、顧客の情報更新追加
app/controllers/public/customers_controller.rb
app/models/customer.rb
app/views/layouts/application.html.erb
app/views/public/customers/edit.html.erb
app/views/public/customers/show.html.erb
app/views/public/homes/top.html.erb
=> add-customer-update

README.md, app/views/layouts/application.html.erb, app/views/public/homes/top.html.erb
=> Feauture top

app/controllers/admin/customers_controller.rb, app/controllers/admin/homes_controller.rb, app/controllers/public/products_controller.rb, app/views/public/products/index.html.erb
=> [update]管理者ページ

app/controllers/public/products_controller.rb, app/models/product.rb, app/views/layouts/application.html.erb, app/views/public/products/index.html.erb, app/views/public/products/show.html.erb
customer側の商品一覧ページと商品詳細ページを追加、修正しました。
=> [add]商品一覧ページ、商品詳細ページ

app/controllers/admin/customers_controller.rb, app/controllers/admin/homes_controller.rb, app/controllers/public/customers_controller.rb, app/controllers/public/sessions_controller.rb, app/views/admin/customers/edit.html.erb, app/views/admin/customers/index.html.erb, app/views/admin/customers/show.html.erb, app/views/admin/homes/top.html.erb, app/views/admin/orders/show.html.erb, app/views/public/customers/withdrawal_check.html.erb, config/initializers/kaminari_config.rb, config/routes.rb
顧客の退会機能を追加しました。
管理者ページにページネーションを追加しました。
modified:   app/controllers/admin/customers_controller.rb
modified:   app/controllers/admin/homes_controller.rb
modified:   app/controllers/public/customers_controller.rb
modified:   app/controllers/public/sessions_controller.rb
modified:   app/views/admin/customers/edit.html.erb
modified:   app/views/admin/customers/index.html.erb
modified:   app/views/admin/customers/show.html.erb
modified:   app/views/admin/homes/top.html.erb
modified:   app/views/admin/orders/show.html.erb
modified:   app/views/public/customers/withdrawal_check.html.erb
modified:   config/initializers/kaminari_config.rb
modified:   config/routes.rb
=> [add]顧客の会員ステータス更新機能

app/controllers/public/carts_controller.rb, app/models/cart.rb, app/models/customer.rb, app/models/product.rb, app/views/public/carts/index.html.erb, app/views/public/products/show.html.erb
=> 商品詳細ページのカート機能保存機能修正完了

app/controllers/public/carts_controller.rb, app/models/cart.rb, app/models/product.rb, app/views/layouts/application.html.erb, app/views/public/carts/index.html.erb, config/application.rb, config/routes.rb
=> カート一覧ページの機能実装完了

app/controllers/admin/orders_controller.rb, app/views/admin/homes/top.html.erb, app/views/admin/orders/show.html.erb, app/views/admin/sessions/new.html.erb, app/views/public/customers/withdrawal_check.html.erb, app/views/public/products/index.html.erb
=> [update]商品一覧ページ

app/controllers/public/carts_controller.rb, app/controllers/public/orders_controller.rb, app/models/cart.rb, app/models/customer.rb, app/models/order.rb, app/models/order_detail.rb, app/models/product.rb, app/models/shopping_address.rb, app/views/public/orders/check.html.erb, app/views/public/orders/index.html.erb, app/views/public/orders/new.html.erb, app/views/public/orders/show.html.erb, config/locales/ja.yml, config/routes.rb
注文機能を実装しました。
app/controllers/public/carts_controller.rb
app/controllers/public/orders_controller.rb
app/models/cart.rb
app/models/customer.rb
app/models/order.rb
app/models/product.rb
app/models/shopping_address.rb
app/views/public/orders/check.html.erb
app/views/public/orders/index.html.erb
app/views/public/orders/new.html.erb
config/locales/ja.yml
config/routes.rb
app/controllers/public/orders_controller.rb
app/views/public/orders/check.html.erb
app/views/public/orders/new.html.erb
app/controllers/public/orders_controller.rb
app/models/order_detail.rb
app/views/public/orders/check.html.erb
app/views/public/orders/new.html.erb
config/locales/ja.yml
app/controllers/public/orders_controller.rb
app/models/order.rb
app/models/order_detail.rb
app/views/public/orders/check.html.erb …
=> Feauture order2

app/controllers/admin/products_controller.rb, app/controllers/public/carts_controller.rb, app/controllers/public/orders_controller.rb, app/models/cart.rb, app/models/product.rb, app/views/layouts/application.html.erb, app/views/public/carts/index.html.erb, app/views/public/customers/edit.html.erb, app/views/public/customers/show.html.erb, app/views/public/orders/check.html.erb, app/views/public/orders/index.html.erb, app/views/public/orders/new.html.erb, app/views/public/orders/show.html.erb, app/views/public/orders/thanx.html.erb, app/views/public/products/index.html.erb, app/views/public/products/show.html.erb, config/application.rb, config/locales/ja.yml, config/routes.rb
以下のファイルを修正しました。
app/controllers/public/carts_controller.rb
app/controllers/public/orders_controller.rb
app/models/cart.rb
app/models/product.rb
app/views/public/carts/index.html.erb
app/views/public/orders/check.html.erb
app/views/public/orders/index.html.erb
app/views/public/orders/new.html.erb
app/views/public/orders/show.html.erb
app/views/public/orders/thanx.html.erb
app/views/public/products/index.html.erb
app/views/public/products/show.html.erb
app/views/public/customers/edit.html.erb
app/views/public/customers/show.html.erb
app/views/layouts/application.html.erb
config/application.rb
config/locales/ja.yml
config/routes.rb
=> Feauture order ditail

app/controllers/public/carts_controller.rb, app/controllers/public/customers_controller.rb, app/models/cart.rb, app/views/layouts/_error_messages.html.erb, app/views/public/carts/index.html.erb, app/views/public/customers/edit.html.erb, app/views/public/products/show.html.erb, config/application.rb, db/migrate/20230217021835_create_carts.rb, db/schema.rb
- カートの挙動の修正
- 同じ商品を追加した時の合計
- エラーメッセージのテンプレート追加　
=> [update]cart

app/controllers/public/carts_controller.rb, app/controllers/public/homes_controller.rb, app/models/cart.rb, app/views/public/carts/index.html.erb, app/views/public/homes/top.html.erb, app/views/public/products/show.html.erb
=> カートページ権限設定済み

app/controllers/public/carts_controller.rb, app/controllers/public/homes_controller.rb, app/controllers/public/products_controller.rb, app/views/admin/products/index.html.erb, app/views/public/homes/top.html.erb, app/views/public/products/_genres_search.html.erb, app/views/public/products/_index.html.erb, app/views/public/products/index.html.erb, app/views/public/products/show.html.erb, config/initializers/kaminari_config.rb
顧客のTOPページと、商品一覧の編集       
modified:   app/controllers/public/carts_controller.rb
modified:   app/controllers/public/homes_controller.rb
modified:   app/controllers/public/products_controller.rb
modified:   app/views/admin/products/index.html.erb
modified:   app/views/public/homes/top.html.erb
new file:   app/views/public/products/_genres_search.html.erb
new file:   app/views/public/products/_index.html.erb
modified:   app/views/public/products/index.html.erb
modified:   app/views/public/products/show.html.erb
modified:   config/initializers/kaminari_config.rb
=> 顧客商品,topページの編集

app/controllers/public/carts_controller.rb, app/controllers/public/shopping_addresses_controller.rb, app/models/cart.rb, app/models/shopping_address.rb, app/views/admin/products/index.html.erb, app/views/public/carts/index.html.erb, app/views/public/customers/edit.html.erb, app/views/public/products/_index.html.erb, app/views/public/products/index.html.erb, app/views/public/products/show.html.erb, app/views/public/shopping_addresses/edit.html.erb, app/views/public/shopping_addresses/index.html.erb, db/migrate/20230219040255_add_product_id_to_carts.rb, db/schema.rb
=> ショッピングアドレスとカートのバリデーションとエラー実装完了

app/models/admin.rb, app/views/admin/homes/top.html.erb, app/views/admin/orders/show.html.erb, app/views/public/products/_index.html.erb, app/views/public/products/index.html.erb
管理者ページの修正を行いました
ステータスの更新
編集機能の更新
=> [update]admin　ステータスの更新

app/models/order.rb, app/views/public/registrations/new.html.erb, app/views/public/sessions/new.html.erb
顧客のログイン画面、新規登録画面のレイアウトの修正を行いました
=> [update]ログイン、新規登録のレイアウトの修正

app/views/admin/product_genres/edit.html.erb, app/views/admin/product_genres/index.html.erb, app/views/admin/products/edit.html.erb, app/views/admin/products/new.html.erb, app/views/admin/products/show.html.erb, app/views/public/registrations/new.html.erb
管理者の商品新規登録、ジャンル登録のレイアウトを修正しました
=> [update]レイアウトを修正しました

app/views/public/carts/index.html.erb, app/views/public/customers/edit.html.erb, app/views/public/homes/top.html.erb, app/views/public/orders/new.html.erb, app/views/public/shopping_addresses/index.html.erb
一部レイアウトの修正をしました。
- 配送先
- 住所入力フォームの長さ
- カート一覧下部レイアウト
=> [update]レイアウト
